### ISSUE TITLE
[Lab 2] Πρόβλημα με το αρχείο cv20_lab2_2_utils

### ISSUE THREAD

**Issue by Con-Fou** [ntua-cvsp-lab/CV_LabSupport#36]
Καλησπέρα,

Όταν κάνω import το βοηθητικό αρχείο που μας δώσατε
`import cv20_lab2_2_utils as p2`
Παίρνω αυτό το σφάλμα:
**ImportError: bad magic number in 'cv20_lab2_2_utils': b'B\r\r\n'**
Δοκίμασα και με το εναλλακτικό αρχείο που δώσατε και πάλι έχω το ίδιο πρόβλημα:
**ImportError: bad magic number in 'cv20_lab2_2_utils_ALT': b'B\r\r\n'**

Μήπως γνωρίζετε ποιο είναι το πρόβλημα;

**Comment by Con-Fou** [comment]
Με εκτέλεση της άσκησης σε περιβάλλον που δημιουργείται με την εντολή που δόθηκε στο εισαγωγικό εργαστήριο, το πρόβλημα λύνεται. 
`conda create -n cv_lab2_env python=3.7 opencv=3.4.2 numpy scikit-learn tqdm matplotlib jupyter nb_conda_kernels
`

**Comment by nkardaris** [comment]
Ναι θέλει python 3.7.
